### ISSUE TITLE
Move framework related content from IMPLEMENTATION_GUIDE for aws-media-insights-engine

### ISSUE THREAD

**Issue by aburkleaux-amazon** [awslabs/aws-media-insights#19]
Most, but not all the content in [IMPLEMENTATION_GUIDE.md](https://github.com/awslabs/aws-media-insights/blob/master/IMPLEMENTATION_GUIDE.md) belongs in the framework repository: https://github.com/awslabs/aws-media-insights-engine.

**Comment by jerryelk** [comment]
I assume once the team considers this complete I can put into the template and then send to TW.

**Comment by ianwow** [comment]
Resolved in https://github.com/awslabs/aws-media-insights/releases/tag/v2.0.3
