### ISSUE TITLE
Allow users to control playback speed in video player

### ISSUE THREAD

**Issue by ianwow** [awslabs/aws-media-insights#28]
A user has requested that we allow users to control playback speed in the video player.

**Comment by lwinzen** [comment]
I am looking for an answer to this as well.

**Comment by ianwow** [comment]
This issue will be resolved in our next release (v2.0.3) planned for Feb 15.

**Comment by ianwow** [comment]
Resolved in https://github.com/awslabs/aws-media-insights/releases/tag/v2.0.3
