### ISSUE TITLE
Readme - needs to explain that ElasticSearch costs $10 / USD / day

### ISSUE THREAD

**Issue by 8secz-johndpope** [awslabs/aws-media-insights#30]
currently there's no way to pause this / which is a pain
https://forums.aws.amazon.com/thread.jspa?threadID=103703

I'm ok to delete - but is there a way to restore it / seems doable in cluster mode.
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html

**Comment by ianwow** [comment]
Thanks for submitting this issue. We published cost info on the [AWS solution page](https://docs.aws.amazon.com/solutions/latest/aws-content-analysis/overview.html) but neglected to also add that to the README. So, I've just added it to the [README](https://github.com/awslabs/aws-media-insights/tree/development#cost), now.

We're planning to release an update to the front-end project this week. This change to the README will be shown in the master branch at that time.

Note, the front-end code lives in a repository separate from MIE, so I've moved this issue there. MIE itself does not involve an Elasticsearch resource.

**Comment by 8secz-johndpope** [comment]
fyi
I understand the engine doesn't depend on ElasticSearch - just the webportal
for your reference 


when we deleted the elastic resource - we can't get the website to show up content and seems like the worker process jobs do actually fail too. Need to retest it with a clean slate. We don't intend to keep the elastic resource portal up.



  MediaInsightsWebApp:
    Condition: DeployDemoSiteCondition
    DependsOn:
      - StringFunctions
      - Analytics
      - MediaInsightsWorkflowApi
      - MediaInsightsDataplaneApiStack
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://'
          - !FindInMap ["SourceCode", "General", "GlobalS3Bucket"]
          - .s3
          - '.amazonaws.com/'
          - !FindInMap
            - SourceCode
            - General
            - TemplateKeyPrefix
          - "/media-insights-webapp.template"
      Parameters:
        DataplaneEndpoint: !GetAtt MediaInsightsDataplaneApiStack.Outputs.EndpointURL
        WorkflowEndpoint: !GetAtt MediaInsightsWorkflowApi.Outputs.EndpointURL
        **ElasticEndpoint**: !GetAtt Analytics.Outputs.ElasticUrl
        DataplaneBucket: !Ref Dataplane
        UserPoolId: !Ref MieUserPool
        IdentityPoolId: !Ref MieIdentityPool
        AwsRegion: !Ref "AWS::Region"
        PoolClientId: !Ref MieWebAppClient

  Analytics:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - MediaInsightsWorkflowApi
      - MediaInsightsDataplaneApiStack
    Properties:
      TemplateURL: !Join
        - ''
        - - 'https://'
          - !FindInMap ["SourceCode", "General", "GlobalS3Bucket"]
          - .s3
          - '.amazonaws.com/'
          - !FindInMap
            - SourceCode
            - General
            - TemplateKeyPrefix
          - "/media-insights-dataplane-streaming-stack.template"
      Parameters:
        DynamoStreamArn:
          Fn::GetAtt:
            - DataplaneTable
            - StreamArn
        DynamoTableArn: !GetAtt DataplaneTable.Arn
        DeployElasticConsumer: Yes


  ElasticsearchEndpoint:
    Description: Endpoint for elasticsearch cluster
    Value: !GetAtt Analytics.Outputs.ElasticUrl

**Comment by ianwow** [comment]
I'm not sure I understand. It sounds like you're trying to use the webapp without Elasticsearch, but that won't work. The webapp requires Elasticsearch.

Any chance you could join the MIE Gitter channel? It might be easier for us to chat there. 
https://gitter.im/awslabs/aws-media-insights-engine?utm_source=share-link&utm_medium=link&utm_campaign=share-link
